// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCsXzuFV9-WtyM6jiFc4UXrvH0GazCrQ',
    appId: '1:1010552092173:web:e74db23fde7644853a8744',
    messagingSenderId: '1010552092173',
    projectId: 'final-chat-fe453',
    authDomain: 'final-chat-fe453.firebaseapp.com',
    storageBucket: 'final-chat-fe453.appspot.com',
    measurementId: 'G-6W4Z4746W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF8Sxltwb_oSESaErCambjRbnFnDUr9ac',
    appId: '1:1010552092173:android:977f06de1f9572903a8744',
    messagingSenderId: '1010552092173',
    projectId: 'final-chat-fe453',
    storageBucket: 'final-chat-fe453.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJZIDtSh47Iq9f9Oif54oZKyHvkWlY7TI',
    appId: '1:1010552092173:ios:350b504ad71ed9503a8744',
    messagingSenderId: '1010552092173',
    projectId: 'final-chat-fe453',
    storageBucket: 'final-chat-fe453.appspot.com',
    iosClientId: '1010552092173-7snihmc30v1vn95ljb74n0ve88spg8gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFinaly',
  );
}
